### ISSUE TITLE
src/ based layout breaks pytest

### ISSUE THREAD

**Issue by bdrung** [saltstack/pytest-salt-factories#55]
During Debian package build, the pytest test cases can easily be executed by running this command in the root directory:
```
python3 -m pytest -ra tests/functional tests/unit
```

Commit 1daf13fd01cf87ecad0fb623e7c7f1ca02e3b902 switches the project to an `src/` based layout and breaks this way of running pytest. Specifying `--rootdir` does not help.

**Comment by s0undt3ch** [comment]
We use nox to run out tests. That ensure we have the required dependencies met to run the tests in a virtualenv and we also install the plugin into that virtualenv.

How does Debian handle any other src based layout python project?

**Comment by s0undt3ch** [comment]
if you dont want to install the plugin, you can set the `PYTHONPATH` to `src/`

**Comment by bdrung** [comment]
On Debian, all dependencies are installed via Debian package. The Debian source package defines all build dependencies that are installed before the package build starts. Then the package is build: configure, build, test, install. These steps depend on the used build system. During the test phase, the code from the working directory is tested. There are also autopkgtest tests that will run test cases against installed packages.

The Debian source package must be self-contained and only depend on code specfied in the build dependencies. It must not fetch data from the Internet. So pip is a no-go.

**Comment by bdrung** [comment]
Setting `PYTHONPATH` does not work:
```
$ PYTHONPATH=src/ python3 -m pytest -ra tests/functional tests/unit 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pytest.py", line 102, in <module>
    raise SystemExit(pytest.main())
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 65, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 213, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3/dist-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 789, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 997, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 943, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 297, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'saltfactories.plugin'
```

**Comment by s0undt3ch** [comment]
And if you make that python path variable the full path to `src`?

There aren't any more pytest plugins that use `src` layout being built by Debian?
That way we would know how we could fix this.

**Comment by bdrung** [comment]
I cannot remember that I packaged a Python module that used `src`. I checked a bunch of [packaged pytest plugins](https://packages.debian.org/search?suite=sid&keywords=python3-pytest), but all checked do not run test cases during build:
* [python-pytest-benchmark](https://buildd.debian.org/status/fetch.php?pkg=python-pytest-benchmark&arch=all&ver=3.2.2-2&stamp=1564838573&raw=0)
* [pytest-cookies](https://buildd.debian.org/status/fetch.php?pkg=pytest-cookies&arch=all&ver=0.4.0-1&stamp=1564163784&raw=0)
* [python-pytest-cov](https://buildd.debian.org/status/fetch.php?pkg=python-pytest-cov&arch=all&ver=2.10.1-1&stamp=1609096975&raw=0)
* [pytest-django](https://buildd.debian.org/status/fetch.php?pkg=pytest-django&arch=all&ver=3.5.1-1&stamp=1565201397&raw=0)
* [pytest-expect](https://buildd.debian.org/status/fetch.php?pkg=pytest-expect&arch=all&ver=1.1.0-2&stamp=1586815988&raw=0)

**Comment by s0undt3ch** [comment]
And if you make that python path variable the full path to src?

**Comment by bdrung** [comment]
I figured out why I got this stack trace: It was caused by an older system installed version of pytest-salt-factories.

When trying to build in a clean environment, I end up in a dependency rabbit burrow: We have in Debian unstable:
* python3-pytest 6.0.2-2
* python3-pytest-helpers-namespace 2019.1.8-1

pytest-salt-factories needs python3-pytest-helpers-namespace >= 2020.3.24 which needs Pytest >= 6.1.1. I am calling it day now.

**Comment by s0undt3ch** [comment]
I can probably cut another release pytest-helpers-namespace if I see that I can lower the pytest dependency.

**Comment by bdrung** [comment]
That would be great.

**Comment by bdrung** [comment]
FTR, I have the Debian package pytest-salt-factories 0.121.1-1 with working pytest on Debian unstable: https://salsa.debian.org/salt-team/pytest-salt-factories/-/commits/master-next

I can use this pytest-salt-factories 0.121.1-1 package combined with the Debian unstable packaging of salt to successfully run the pytest on the salt master branch during Debian package build.

**Comment by s0undt3ch** [comment]
Just noticed that this package also requires Pytest >= 6.1.1

**Comment by bdrung** [comment]
Despite that I was able to use python3-pytest 6.0.2-2, but I am only running the functional and unit tests.

**Comment by s0undt3ch** [comment]
Dropped pytest requirement to 6.0.0 for pytest-helpers-namespace and released v2021.4.29
Will drop it on pytest-salt-factories too.

**Comment by s0undt3ch** [comment]
Done. Both plugins now require PyTest 6.0.0

**Comment by bdrung** [comment]
Thanks. I successfully tested the master branch with pytest-helpers-namespace 2021.4.29-1 using:
```
PYTHONPATH=src python3 -m pytest -ra tests/functional tests/unit
```

So setting `PYTHONPATH=src` allows running pytests after the layout change.
